version: '3'

services:
  squid-proxy:
    build:
      context: .
      dockerfile: Dockerfile.squid-proxy
    image: squid-proxy
    ports:
      - "3128:3128"
    volumes:
      - squid-cache:/var/cache/squid
      - ssl-cert:/etc/squid/ssl_cert
    restart: always

  lighttpd:
    image: sebp/lighttpd
    volumes:
      - ssl-cert:/var/www/localhost/htdocs
    ports:
      - "3129:80"

volumes:
  squid-cache:
  ssl-cert:
